sneedif: mark as broken
Builds fails with:

    Running phase: buildPhase
    build flags: -j32
    [1/4] Compiling C++ object libsneedif.so.p/SNEEDIF_vectorclass_instrset_detect.cpp.o
    [2/4] Compiling C++ object libsneedif.so.p/SNEEDIF_SNEEDIF.cpp.o
    FAILED: [code=1] libsneedif.so.p/SNEEDIF_SNEEDIF.cpp.o
    g++ -Ilibsneedif.so.p -I. -I.. -I/nix/store/z6j34sx2b9jd4z61ns1m04y7mrmxhnsm-vapoursynth-72/include/vapoursynth -I/nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include -I/nix/store/5hnqsfc2l1q56zi898bnk8ik3f9gl7b9-opencl-headers-2025.07.22/include -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++20 -O3 -ffast-math '-DNNEDI3_DATADIR="/nix/store/2dgisjsb5fx9f5m9v0k8dahgx6dcnjyd-sneedif-3/share/SNEEDIF"' -Wno-unused-variable -Wno-ignored-attributes -Wno-sign-compare -Wno-narrowing -Wno-int-in-bool-context -ffast-math -mfpmath=sse -msse2 -fPIC -DBOOST_FILESYSTEM_DYN_LINK=1 -DBOOST_ALL_NO_LIB -MD -MQ libsneedif.so.p/SNEEDIF_SNEEDIF.cpp.o -MF libsneedif.so.p/SNEEDIF_SNEEDIF.cpp.o.d -o libsneedif.so.p/SNEEDIF_SNEEDIF.cpp.o -c ../SNEEDIF/SNEEDIF.cpp
    In file included from /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/command_queue.hpp:26,
                     from /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/core.hpp:19,
                     from ../SNEEDIF/shared.hpp:37,
                     from ../SNEEDIF/SNEEDIF.cpp:1:
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image1d.hpp: In constructor 'boost::compute::image1d::image1d(const boost::compute::context&, size_t, const boost::compute::image_format&, cl_mem_flags, void*)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image1d.hpp:65:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
       65 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    In file included from /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/command_queue.hpp:27:
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image2d.hpp: In constructor 'boost::compute::image2d::image2d(const boost::compute::context&, size_t, size_t, const boost::compute::image_format&, cl_mem_flags, void*, size_t)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image2d.hpp:73:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
       73 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image2d.hpp: In constructor 'boost::compute::image2d::image2d(const boost::compute::context&, cl_mem_flags, const boost::compute::image_format&, size_t, size_t, size_t, void*)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image2d.hpp:123:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
      123 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    In file included from /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/command_queue.hpp:28:
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image3d.hpp: In constructor 'boost::compute::image3d::image3d(const boost::compute::context&, size_t, size_t, size_t, const boost::compute::image_format&, cl_mem_flags, void*, size_t, size_t)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image3d.hpp:69:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
       69 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image3d.hpp: In constructor 'boost::compute::image3d::image3d(const boost::compute::context&, cl_mem_flags, const boost::compute::image_format&, size_t, size_t, size_t, size_t, size_t, void*)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image3d.hpp:123:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
      123 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    [3/4] Compiling C++ object libsneedif.so.p/SNEEDIF_NNEDI3.cpp.o
    FAILED: [code=1] libsneedif.so.p/SNEEDIF_NNEDI3.cpp.o
    g++ -Ilibsneedif.so.p -I. -I.. -I/nix/store/z6j34sx2b9jd4z61ns1m04y7mrmxhnsm-vapoursynth-72/include/vapoursynth -I/nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include -I/nix/store/5hnqsfc2l1q56zi898bnk8ik3f9gl7b9-opencl-headers-2025.07.22/include -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++20 -O3 -ffast-math '-DNNEDI3_DATADIR="/nix/store/2dgisjsb5fx9f5m9v0k8dahgx6dcnjyd-sneedif-3/share/SNEEDIF"' -Wno-unused-variable -Wno-ignored-attributes -Wno-sign-compare -Wno-narrowing -Wno-int-in-bool-context -ffast-math -mfpmath=sse -msse2 -fPIC -DBOOST_FILESYSTEM_DYN_LINK=1 -DBOOST_ALL_NO_LIB -MD -MQ libsneedif.so.p/SNEEDIF_NNEDI3.cpp.o -MF libsneedif.so.p/SNEEDIF_NNEDI3.cpp.o.d -o libsneedif.so.p/SNEEDIF_NNEDI3.cpp.o -c ../SNEEDIF/NNEDI3.cpp
    In file included from /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/command_queue.hpp:26,
                     from /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/core.hpp:19,
                     from ../SNEEDIF/shared.hpp:37,
                     from ../SNEEDIF/NNEDI3.cpp:7:
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image1d.hpp: In constructor 'boost::compute::image1d::image1d(const boost::compute::context&, size_t, const boost::compute::image_format&, cl_mem_flags, void*)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image1d.hpp:65:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
       65 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    In file included from /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/command_queue.hpp:27:
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image2d.hpp: In constructor 'boost::compute::image2d::image2d(const boost::compute::context&, size_t, size_t, const boost::compute::image_format&, cl_mem_flags, void*, size_t)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image2d.hpp:73:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
       73 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image2d.hpp: In constructor 'boost::compute::image2d::image2d(const boost::compute::context&, cl_mem_flags, const boost::compute::image_format&, size_t, size_t, size_t, void*)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image2d.hpp:123:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
      123 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    In file included from /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/command_queue.hpp:28:
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image3d.hpp: In constructor 'boost::compute::image3d::image3d(const boost::compute::context&, size_t, size_t, size_t, const boost::compute::image_format&, cl_mem_flags, void*, size_t, size_t)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image3d.hpp:69:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
       69 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image3d.hpp: In constructor 'boost::compute::image3d::image3d(const boost::compute::context&, cl_mem_flags, const boost::compute::image_format&, size_t, size_t, size_t, size_t, size_t, void*)':
    /nix/store/pfljy718vzlbycg1l9rzzh8rpzcjg9il-boost-1.87.0-dev/include/boost/compute/image/image3d.hpp:123:14: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
      123 |         desc.mem_object = 0;
          |              ^~~~~~~~~~
    ../SNEEDIF/NNEDI3.cpp: In function 'void nnedi3Create(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*)':
    ../SNEEDIF/NNEDI3.cpp:610:18: error: 'cl_image_desc' {aka 'struct _cl_image_desc'} has no member named 'mem_object'
      610 |             desc.mem_object = d->weights1Buffer.get();
          |                  ^~~~~~~~~~
    ninja: build stopped: subcommand failed.
    error: builder for '/nix/store/cfhapcfdwphv31alc0z309apidf6dx9i-sneedif-3.drv' failed with exit code 1